/* ============================================================
   Base de données — détachée de l'interface (index.html)
   Schéma : { t: titre, plat: "netflix|prime|disney",
              type: "film|serie", rating: note/10, year, genre }
   Disponibilités indicatives (France), susceptibles d'évoluer.
   ============================================================ */
window.DATA = [

  /* ===================== NETFLIX ===================== */
  {t:"Breaking Bad", plat:"netflix", type:"serie", rating:9.5, year:2008, genre:"Crime · Drame"},
  {t:"Better Call Saul", plat:"netflix", type:"serie", rating:9.0, year:2015, genre:"Crime · Drame"},
  {t:"The Last Dance", plat:"netflix", type:"serie", rating:9.0, year:2020, genre:"Documentaire"},
  {t:"Arcane", plat:"netflix", type:"serie", rating:9.0, year:2021, genre:"Animation · SF"},
  {t:"When They See Us", plat:"netflix", type:"serie", rating:8.9, year:2019, genre:"Drame"},
  {t:"Peaky Blinders", plat:"netflix", type:"serie", rating:8.8, year:2013, genre:"Crime · Drame"},
  {t:"Narcos", plat:"netflix", type:"serie", rating:8.8, year:2015, genre:"Crime · Biopic"},
  {t:"BoJack Horseman", plat:"netflix", type:"serie", rating:8.8, year:2014, genre:"Animation · Comédie"},
  {t:"Dark", plat:"netflix", type:"serie", rating:8.7, year:2017, genre:"SF · Thriller"},
  {t:"Stranger Things", plat:"netflix", type:"serie", rating:8.7, year:2016, genre:"SF · Horreur"},
  {t:"Black Mirror", plat:"netflix", type:"serie", rating:8.7, year:2011, genre:"SF · Anthologie"},
  {t:"The Haunting of Hill House", plat:"netflix", type:"serie", rating:8.6, year:2018, genre:"Horreur · Drame"},
  {t:"Mindhunter", plat:"netflix", type:"serie", rating:8.6, year:2017, genre:"Crime · Thriller"},
  {t:"The Crown", plat:"netflix", type:"serie", rating:8.6, year:2016, genre:"Drame · Historique"},
  {t:"Ozark", plat:"netflix", type:"serie", rating:8.5, year:2017, genre:"Crime · Thriller"},
  {t:"Cobra Kai", plat:"netflix", type:"serie", rating:8.5, year:2018, genre:"Action · Comédie"},
  {t:"Le Jeu de la dame", plat:"netflix", type:"serie", rating:8.5, year:2020, genre:"Drame"},
  {t:"Love, Death & Robots", plat:"netflix", type:"serie", rating:8.4, year:2019, genre:"Animation · SF"},
  {t:"After Life", plat:"netflix", type:"serie", rating:8.4, year:2019, genre:"Comédie · Drame"},
  {t:"The Last Kingdom", plat:"netflix", type:"serie", rating:8.4, year:2015, genre:"Historique · Action"},
  {t:"Castlevania", plat:"netflix", type:"serie", rating:8.3, year:2017, genre:"Animation · Fantastique"},
  {t:"Sex Education", plat:"netflix", type:"serie", rating:8.3, year:2019, genre:"Comédie · Drame"},
  {t:"Kingdom", plat:"netflix", type:"serie", rating:8.3, year:2019, genre:"Horreur · Historique"},
  {t:"Fauda", plat:"netflix", type:"serie", rating:8.3, year:2015, genre:"Thriller · Action"},
  {t:"Narcos: Mexico", plat:"netflix", type:"serie", rating:8.3, year:2018, genre:"Crime · Biopic"},
  {t:"Heartstopper", plat:"netflix", type:"serie", rating:8.2, year:2022, genre:"Romance · Drame"},
  {t:"Sense8", plat:"netflix", type:"serie", rating:8.2, year:2015, genre:"SF · Drame"},
  {t:"La Casa de Papel", plat:"netflix", type:"serie", rating:8.2, year:2017, genre:"Braquage · Thriller"},
  {t:"Lucifer", plat:"netflix", type:"serie", rating:8.1, year:2016, genre:"Fantastique · Crime"},
  {t:"Mercredi", plat:"netflix", type:"serie", rating:8.1, year:2022, genre:"Comédie · Fantastique"},
  {t:"Squid Game", plat:"netflix", type:"serie", rating:8.0, year:2021, genre:"Thriller · Drame"},
  {t:"The Witcher", plat:"netflix", type:"serie", rating:8.0, year:2019, genre:"Fantastique · Aventure"},
  {t:"Unorthodox", plat:"netflix", type:"serie", rating:8.0, year:2020, genre:"Drame"},
  {t:"GLOW", plat:"netflix", type:"serie", rating:8.0, year:2017, genre:"Comédie · Drame"},
  {t:"Beef", plat:"netflix", type:"serie", rating:8.0, year:2023, genre:"Comédie · Drame"},
  {t:"Dahmer", plat:"netflix", type:"serie", rating:8.0, year:2022, genre:"Crime · Drame"},
  {t:"The Diplomat", plat:"netflix", type:"serie", rating:8.0, year:2023, genre:"Thriller · Drame"},
  {t:"One Piece", plat:"netflix", type:"serie", rating:8.0, year:2023, genre:"Aventure · Action"},
  {t:"Ripley", plat:"netflix", type:"serie", rating:8.0, year:2024, genre:"Thriller · Drame"},
  {t:"The Umbrella Academy", plat:"netflix", type:"serie", rating:7.9, year:2019, genre:"SF · Action"},
  {t:"The Sinner", plat:"netflix", type:"serie", rating:7.9, year:2017, genre:"Crime · Thriller"},
  {t:"The OA", plat:"netflix", type:"serie", rating:7.8, year:2016, genre:"SF · Mystère"},
  {t:"Baby Reindeer", plat:"netflix", type:"serie", rating:7.8, year:2024, genre:"Drame · Thriller"},
  {t:"You", plat:"netflix", type:"serie", rating:7.7, year:2018, genre:"Thriller · Drame"},
  {t:"Russian Doll", plat:"netflix", type:"serie", rating:7.7, year:2019, genre:"SF · Comédie"},
  {t:"Maniac", plat:"netflix", type:"serie", rating:7.7, year:2018, genre:"SF · Drame"},
  {t:"Sweet Tooth", plat:"netflix", type:"serie", rating:7.7, year:2021, genre:"Aventure · Fantastique"},
  {t:"Sandman", plat:"netflix", type:"serie", rating:7.7, year:2022, genre:"Fantastique · Drame"},
  {t:"Alice in Borderland", plat:"netflix", type:"serie", rating:7.6, year:2020, genre:"Thriller · SF"},
  {t:"Lupin", plat:"netflix", type:"serie", rating:7.5, year:2021, genre:"Policier · Aventure"},
  {t:"Shadow and Bone", plat:"netflix", type:"serie", rating:7.5, year:2021, genre:"Fantastique · Aventure"},
  {t:"The Night Agent", plat:"netflix", type:"serie", rating:7.5, year:2023, genre:"Action · Thriller"},
  {t:"Outer Banks", plat:"netflix", type:"serie", rating:7.5, year:2020, genre:"Aventure · Drame"},
  {t:"The Empress", plat:"netflix", type:"serie", rating:7.5, year:2022, genre:"Drame · Historique"},
  {t:"Élite", plat:"netflix", type:"serie", rating:7.4, year:2018, genre:"Drame · Thriller"},
  {t:"1899", plat:"netflix", type:"serie", rating:7.4, year:2022, genre:"Mystère · SF"},
  {t:"Bridgerton", plat:"netflix", type:"serie", rating:7.3, year:2020, genre:"Romance · Drame"},
  {t:"Ginny & Georgia", plat:"netflix", type:"serie", rating:7.3, year:2021, genre:"Comédie · Drame"},
  {t:"Disenchantment", plat:"netflix", type:"serie", rating:7.2, year:2018, genre:"Animation · Comédie"},
  {t:"Marco Polo", plat:"netflix", type:"serie", rating:8.0, year:2014, genre:"Historique · Drame"},
  {t:"Klaus", plat:"netflix", type:"film", rating:8.1, year:2019, genre:"Animation · Famille"},
  {t:"Marriage Story", plat:"netflix", type:"film", rating:7.9, year:2019, genre:"Drame"},
  {t:"The Irishman", plat:"netflix", type:"film", rating:7.8, year:2019, genre:"Crime · Drame"},
  {t:"À l'Ouest, rien de nouveau", plat:"netflix", type:"film", rating:7.8, year:2022, genre:"Guerre · Drame"},
  {t:"Le Cercle des neiges", plat:"netflix", type:"film", rating:7.8, year:2023, genre:"Drame · Survie"},
  {t:"Roma", plat:"netflix", type:"film", rating:7.7, year:2018, genre:"Drame"},
  {t:"Les Sept de Chicago", plat:"netflix", type:"film", rating:7.7, year:2020, genre:"Drame · Historique"},
  {t:"Beasts of No Nation", plat:"netflix", type:"film", rating:7.7, year:2015, genre:"Guerre · Drame"},
  {t:"Les Deux Papes", plat:"netflix", type:"film", rating:7.6, year:2019, genre:"Drame"},
  {t:"Les Misérables", plat:"netflix", type:"film", rating:7.6, year:2019, genre:"Drame"},
  {t:"Pinocchio par Guillermo del Toro", plat:"netflix", type:"film", rating:7.6, year:2022, genre:"Animation · Fantastique"},
  {t:"The Mitchells contre les machines", plat:"netflix", type:"film", rating:7.6, year:2021, genre:"Animation · Comédie"},
  {t:"J'ai perdu mon corps", plat:"netflix", type:"film", rating:7.5, year:2019, genre:"Animation · Drame"},
  {t:"Nimona", plat:"netflix", type:"film", rating:7.5, year:2023, genre:"Animation · Aventure"},
  {t:"Mudbound", plat:"netflix", type:"film", rating:7.4, year:2017, genre:"Drame · Historique"},
  {t:"Uncut Gems", plat:"netflix", type:"film", rating:7.4, year:2019, genre:"Thriller · Drame"},
  {t:"Okja", plat:"netflix", type:"film", rating:7.3, year:2017, genre:"Aventure · SF"},
  {t:"Don't Look Up", plat:"netflix", type:"film", rating:7.2, year:2021, genre:"Comédie · SF"},
  {t:"The Ballad of Buster Scruggs", plat:"netflix", type:"film", rating:7.2, year:2018, genre:"Western · Comédie"},
  {t:"Glass Onion", plat:"netflix", type:"film", rating:7.1, year:2022, genre:"Policier · Comédie"},
  {t:"The Platform", plat:"netflix", type:"film", rating:7.0, year:2019, genre:"SF · Horreur"},
  {t:"The Sea Beast", plat:"netflix", type:"film", rating:7.0, year:2022, genre:"Animation · Aventure"},
  {t:"May December", plat:"netflix", type:"film", rating:7.0, year:2023, genre:"Drame"},
  {t:"Rebel Ridge", plat:"netflix", type:"film", rating:7.0, year:2024, genre:"Action · Thriller"},
  {t:"Hit Man", plat:"netflix", type:"film", rating:6.9, year:2023, genre:"Comédie · Action"},
  {t:"The Power of the Dog", plat:"netflix", type:"film", rating:6.8, year:2021, genre:"Drame · Western"},
  {t:"BAC Nord", plat:"netflix", type:"film", rating:6.8, year:2020, genre:"Policier · Action"},
  {t:"The Killer", plat:"netflix", type:"film", rating:6.7, year:2023, genre:"Thriller · Crime"},
  {t:"Extraction", plat:"netflix", type:"film", rating:6.7, year:2020, genre:"Action · Thriller"},
  {t:"The Adam Project", plat:"netflix", type:"film", rating:6.7, year:2022, genre:"SF · Aventure"},
  {t:"The Wonder", plat:"netflix", type:"film", rating:6.7, year:2022, genre:"Drame · Mystère"},
  {t:"Bird Box", plat:"netflix", type:"film", rating:6.6, year:2018, genre:"Horreur · Thriller"},
  {t:"Enola Holmes", plat:"netflix", type:"film", rating:6.6, year:2020, genre:"Aventure · Policier"},
  {t:"Maestro", plat:"netflix", type:"film", rating:6.6, year:2023, genre:"Drame · Biopic"},
  {t:"Athena", plat:"netflix", type:"film", rating:6.5, year:2022, genre:"Drame · Action"},
  {t:"The Gray Man", plat:"netflix", type:"film", rating:6.5, year:2022, genre:"Action · Thriller"},
  {t:"His House", plat:"netflix", type:"film", rating:6.5, year:2020, genre:"Horreur · Drame"},
  {t:"Carry-On", plat:"netflix", type:"film", rating:6.5, year:2024, genre:"Thriller · Action"},
  {t:"Leave the World Behind", plat:"netflix", type:"film", rating:6.5, year:2023, genre:"Thriller · Drame"},
  {t:"Damsel", plat:"netflix", type:"film", rating:6.1, year:2024, genre:"Fantastique · Action"},

  /* ===================== PRIME VIDEO ===================== */
  {t:"Clarkson's Farm", plat:"prime", type:"serie", rating:9.0, year:2021, genre:"Documentaire · Comédie"},
  {t:"The Boys", plat:"prime", type:"serie", rating:8.7, year:2019, genre:"Super-héros · Action"},
  {t:"The Marvelous Mrs. Maisel", plat:"prime", type:"serie", rating:8.7, year:2017, genre:"Comédie · Drame"},
  {t:"Fleabag", plat:"prime", type:"serie", rating:8.7, year:2016, genre:"Comédie · Drame"},
  {t:"Invincible", plat:"prime", type:"serie", rating:8.7, year:2021, genre:"Animation · Super-héros"},
  {t:"The Grand Tour", plat:"prime", type:"serie", rating:8.7, year:2016, genre:"Documentaire · Comédie"},
  {t:"Mr. Robot", plat:"prime", type:"serie", rating:8.5, year:2015, genre:"Thriller · Drame"},
  {t:"Bosch", plat:"prime", type:"serie", rating:8.5, year:2014, genre:"Policier · Crime"},
  {t:"The Expanse", plat:"prime", type:"serie", rating:8.5, year:2015, genre:"SF · Drame"},
  {t:"Vikings", plat:"prime", type:"serie", rating:8.5, year:2013, genre:"Historique · Action"},
  {t:"Fallout", plat:"prime", type:"serie", rating:8.4, year:2024, genre:"SF · Aventure"},
  {t:"Undone", plat:"prime", type:"serie", rating:8.2, year:2019, genre:"Animation · Drame"},
  {t:"Patriot", plat:"prime", type:"serie", rating:8.2, year:2015, genre:"Comédie · Drame"},
  {t:"Sneaky Pete", plat:"prime", type:"serie", rating:8.2, year:2015, genre:"Crime · Drame"},
  {t:"Bosch: Legacy", plat:"prime", type:"serie", rating:8.2, year:2022, genre:"Policier · Crime"},
  {t:"Reacher", plat:"prime", type:"serie", rating:8.1, year:2022, genre:"Action · Thriller"},
  {t:"Jack Ryan", plat:"prime", type:"serie", rating:8.0, year:2018, genre:"Action · Thriller"},
  {t:"The Terminal List", plat:"prime", type:"serie", rating:8.0, year:2022, genre:"Action · Thriller"},
  {t:"Good Omens", plat:"prime", type:"serie", rating:8.0, year:2019, genre:"Fantastique · Comédie"},
  {t:"Wilfred", plat:"prime", type:"serie", rating:8.0, year:2011, genre:"Comédie · Drame"},
  {t:"Upload", plat:"prime", type:"serie", rating:7.9, year:2020, genre:"Comédie · SF"},
  {t:"Goliath", plat:"prime", type:"serie", rating:7.8, year:2016, genre:"Drame · Policier"},
  {t:"Gen V", plat:"prime", type:"serie", rating:7.8, year:2023, genre:"Super-héros · Action"},
  {t:"American Gods", plat:"prime", type:"serie", rating:7.6, year:2017, genre:"Fantastique · Drame"},
  {t:"Modern Love", plat:"prime", type:"serie", rating:7.6, year:2019, genre:"Romance · Drame"},
  {t:"Hanna", plat:"prime", type:"serie", rating:7.5, year:2019, genre:"Action · Thriller"},
  {t:"Carnival Row", plat:"prime", type:"serie", rating:7.5, year:2019, genre:"Fantastique · Crime"},
  {t:"The Peripheral", plat:"prime", type:"serie", rating:7.5, year:2022, genre:"SF · Thriller"},
  {t:"Daisy Jones & The Six", plat:"prime", type:"serie", rating:7.5, year:2023, genre:"Drame · Musique"},
  {t:"The Summer I Turned Pretty", plat:"prime", type:"serie", rating:7.5, year:2022, genre:"Romance · Drame"},
  {t:"Homecoming", plat:"prime", type:"serie", rating:7.4, year:2018, genre:"Thriller · Drame"},
  {t:"The Wilds", plat:"prime", type:"serie", rating:7.4, year:2020, genre:"Drame · Mystère"},
  {t:"Outer Range", plat:"prime", type:"serie", rating:7.2, year:2022, genre:"Mystère · Western"},
  {t:"Hunters", plat:"prime", type:"serie", rating:7.2, year:2020, genre:"Thriller · Drame"},
  {t:"Mr. & Mrs. Smith", plat:"prime", type:"serie", rating:7.2, year:2024, genre:"Action · Comédie"},
  {t:"La Roue du Temps", plat:"prime", type:"serie", rating:7.1, year:2021, genre:"Fantastique"},
  {t:"The Boys Presents: Diabolical", plat:"prime", type:"serie", rating:7.0, year:2022, genre:"Animation · Comédie"},
  {t:"Les Anneaux de Pouvoir", plat:"prime", type:"serie", rating:6.9, year:2022, genre:"Fantastique · Aventure"},
  {t:"The Power", plat:"prime", type:"serie", rating:6.8, year:2023, genre:"SF · Drame"},
  {t:"Citadel", plat:"prime", type:"serie", rating:6.2, year:2023, genre:"Action · Thriller"},
  {t:"Le Parrain", plat:"prime", type:"film", rating:9.2, year:1972, genre:"Crime · Drame"},
  {t:"Le Parrain, 2e partie", plat:"prime", type:"film", rating:9.0, year:1974, genre:"Crime · Drame"},
  {t:"Pulp Fiction", plat:"prime", type:"film", rating:8.9, year:1994, genre:"Crime · Drame"},
  {t:"Forrest Gump", plat:"prime", type:"film", rating:8.8, year:1994, genre:"Drame · Romance"},
  {t:"Inception", plat:"prime", type:"film", rating:8.8, year:2010, genre:"SF · Thriller"},
  {t:"Interstellar", plat:"prime", type:"film", rating:8.7, year:2014, genre:"SF · Aventure"},
  {t:"Le Silence des agneaux", plat:"prime", type:"film", rating:8.6, year:1991, genre:"Thriller · Crime"},
  {t:"Gladiator", plat:"prime", type:"film", rating:8.5, year:2000, genre:"Action · Historique"},
  {t:"Whiplash", plat:"prime", type:"film", rating:8.5, year:2014, genre:"Drame · Musique"},
  {t:"Parasite", plat:"prime", type:"film", rating:8.5, year:2019, genre:"Thriller · Drame"},
  {t:"Joker", plat:"prime", type:"film", rating:8.4, year:2019, genre:"Drame · Thriller"},
  {t:"Le Loup de Wall Street", plat:"prime", type:"film", rating:8.2, year:2013, genre:"Biopic · Comédie"},
  {t:"Prisoners", plat:"prime", type:"film", rating:8.2, year:2013, genre:"Thriller · Crime"},
  {t:"The Father", plat:"prime", type:"film", rating:8.2, year:2020, genre:"Drame"},
  {t:"Three Billboards", plat:"prime", type:"film", rating:8.1, year:2017, genre:"Drame · Crime"},
  {t:"Gone Girl", plat:"prime", type:"film", rating:8.1, year:2014, genre:"Thriller · Drame"},
  {t:"12 Years a Slave", plat:"prime", type:"film", rating:8.1, year:2013, genre:"Drame · Historique"},
  {t:"Spotlight", plat:"prime", type:"film", rating:8.1, year:2015, genre:"Drame"},
  {t:"The Grand Budapest Hotel", plat:"prime", type:"film", rating:8.1, year:2014, genre:"Comédie · Aventure"},
  {t:"Mad Max: Fury Road", plat:"prime", type:"film", rating:8.1, year:2015, genre:"Action · SF"},
  {t:"Le Discours d'un roi", plat:"prime", type:"film", rating:8.0, year:2010, genre:"Drame · Historique"},
  {t:"La La Land", plat:"prime", type:"film", rating:8.0, year:2016, genre:"Comédie musicale · Romance"},
  {t:"Blade Runner 2049", plat:"prime", type:"film", rating:8.0, year:2017, genre:"SF · Drame"},
  {t:"The Revenant", plat:"prime", type:"film", rating:8.0, year:2015, genre:"Aventure · Drame"},
  {t:"Premier Contact", plat:"prime", type:"film", rating:7.9, year:2016, genre:"SF · Drame"},
  {t:"Everything Everywhere All at Once", plat:"prime", type:"film", rating:7.8, year:2022, genre:"SF · Aventure"},
  {t:"Manchester by the Sea", plat:"prime", type:"film", rating:7.8, year:2016, genre:"Drame"},
  {t:"The Big Short", plat:"prime", type:"film", rating:7.8, year:2015, genre:"Drame · Comédie"},
  {t:"Call Me by Your Name", plat:"prime", type:"film", rating:7.8, year:2017, genre:"Romance · Drame"},
  {t:"Past Lives", plat:"prime", type:"film", rating:7.8, year:2023, genre:"Romance · Drame"},
  {t:"Le Comte de Monte-Cristo", plat:"prime", type:"film", rating:7.8, year:2024, genre:"Aventure · Drame"},
  {t:"Nightcrawler", plat:"prime", type:"film", rating:7.8, year:2014, genre:"Thriller · Crime"},
  {t:"Drive", plat:"prime", type:"film", rating:7.8, year:2011, genre:"Action · Drame"},
  {t:"The Social Network", plat:"prime", type:"film", rating:7.8, year:2010, genre:"Drame · Biopic"},
  {t:"Ex Machina", plat:"prime", type:"film", rating:7.7, year:2014, genre:"SF · Thriller"},
  {t:"Birdman", plat:"prime", type:"film", rating:7.7, year:2014, genre:"Drame · Comédie"},
  {t:"Sound of Metal", plat:"prime", type:"film", rating:7.7, year:2019, genre:"Drame · Musique"},
  {t:"Anatomie d'une chute", plat:"prime", type:"film", rating:7.6, year:2023, genre:"Drame · Thriller"},
  {t:"Sicario", plat:"prime", type:"film", rating:7.6, year:2015, genre:"Thriller · Crime"},
  {t:"Aftersun", plat:"prime", type:"film", rating:7.6, year:2022, genre:"Drame"},
  {t:"The Florida Project", plat:"prime", type:"film", rating:7.6, year:2017, genre:"Drame"},
  {t:"The Big Sick", plat:"prime", type:"film", rating:7.5, year:2017, genre:"Comédie · Romance"},
  {t:"American Fiction", plat:"prime", type:"film", rating:7.4, year:2023, genre:"Comédie · Drame"},
  {t:"Lady Bird", plat:"prime", type:"film", rating:7.4, year:2017, genre:"Comédie · Drame"},
  {t:"Moonlight", plat:"prime", type:"film", rating:7.4, year:2016, genre:"Drame"},
  {t:"Air", plat:"prime", type:"film", rating:7.4, year:2023, genre:"Drame · Biopic"},
  {t:"Nomadland", plat:"prime", type:"film", rating:7.3, year:2020, genre:"Drame"},
  {t:"Hereditary", plat:"prime", type:"film", rating:7.3, year:2018, genre:"Horreur · Drame"},
  {t:"Le Report", plat:"prime", type:"film", rating:7.2, year:2019, genre:"Drame · Thriller"},
  {t:"Midsommar", plat:"prime", type:"film", rating:7.1, year:2019, genre:"Horreur · Drame"},
  {t:"One Night in Miami", plat:"prime", type:"film", rating:7.1, year:2020, genre:"Drame · Historique"},
  {t:"The Witch", plat:"prime", type:"film", rating:7.0, year:2015, genre:"Horreur"},
  {t:"Saltburn", plat:"prime", type:"film", rating:7.0, year:2023, genre:"Drame · Thriller"},
  {t:"The Burial", plat:"prime", type:"film", rating:7.0, year:2023, genre:"Drame"},
  {t:"The Aeronauts", plat:"prime", type:"film", rating:6.6, year:2019, genre:"Aventure · Drame"},
  {t:"The Tomorrow War", plat:"prime", type:"film", rating:6.5, year:2021, genre:"SF · Action"},
  {t:"The Idea of You", plat:"prime", type:"film", rating:6.4, year:2024, genre:"Romance · Drame"},
  {t:"The Lost City", plat:"prime", type:"film", rating:6.1, year:2022, genre:"Comédie · Aventure"},
  {t:"Road House", plat:"prime", type:"film", rating:6.0, year:2024, genre:"Action"},
  {t:"Il faut sauver le soldat Ryan", plat:"prime", type:"film", rating:8.6, year:1998, genre:"Guerre · Drame"},

  /* ===================== DISNEY+ ===================== */
  {t:"Fargo", plat:"disney", type:"serie", rating:8.9, year:2014, genre:"Crime · Drame"},
  {t:"It's Always Sunny in Philadelphia", plat:"disney", type:"serie", rating:8.8, year:2005, genre:"Comédie"},
  {t:"Les Simpson", plat:"disney", type:"serie", rating:8.7, year:1989, genre:"Animation · Comédie"},
  {t:"The Mandalorian", plat:"disney", type:"serie", rating:8.7, year:2019, genre:"SF · Aventure"},
  {t:"This Is Us", plat:"disney", type:"serie", rating:8.7, year:2016, genre:"Drame"},
  {t:"Shogun", plat:"disney", type:"serie", rating:8.7, year:2024, genre:"Historique · Drame"},
  {t:"Daredevil", plat:"disney", type:"serie", rating:8.6, year:2015, genre:"Super-héros · Action"},
  {t:"Sons of Anarchy", plat:"disney", type:"serie", rating:8.6, year:2008, genre:"Crime · Drame"},
  {t:"Atlanta", plat:"disney", type:"serie", rating:8.6, year:2016, genre:"Comédie · Drame"},
  {t:"The Bear", plat:"disney", type:"serie", rating:8.6, year:2022, genre:"Comédie · Drame"},
  {t:"Aux frontières du réel (X-Files)", plat:"disney", type:"serie", rating:8.6, year:1993, genre:"SF · Mystère"},
  {t:"Modern Family", plat:"disney", type:"serie", rating:8.5, year:2009, genre:"Comédie"},
  {t:"The Punisher", plat:"disney", type:"serie", rating:8.5, year:2017, genre:"Action · Crime"},
  {t:"Welcome to Wrexham", plat:"disney", type:"serie", rating:8.5, year:2022, genre:"Documentaire"},
  {t:"Futurama", plat:"disney", type:"serie", rating:8.5, year:1999, genre:"Animation · Comédie"},
  {t:"24 heures chrono", plat:"disney", type:"serie", rating:8.4, year:2001, genre:"Action · Thriller"},
  {t:"Andor", plat:"disney", type:"serie", rating:8.4, year:2022, genre:"SF · Drame"},
  {t:"The Clone Wars", plat:"disney", type:"serie", rating:8.4, year:2008, genre:"Animation · SF"},
  {t:"The Americans", plat:"disney", type:"serie", rating:8.4, year:2013, genre:"Drame · Thriller"},
  {t:"Les Disparus (Lost)", plat:"disney", type:"serie", rating:8.3, year:2004, genre:"Drame · Mystère"},
  {t:"Prison Break", plat:"disney", type:"serie", rating:8.3, year:2005, genre:"Action · Thriller"},
  {t:"How I Met Your Mother", plat:"disney", type:"serie", rating:8.3, year:2005, genre:"Comédie"},
  {t:"Buffy contre les vampires", plat:"disney", type:"serie", rating:8.3, year:1997, genre:"Fantastique · Action"},
  {t:"Loki", plat:"disney", type:"serie", rating:8.2, year:2021, genre:"SF · Aventure"},
  {t:"Bob's Burgers", plat:"disney", type:"serie", rating:8.2, year:2011, genre:"Animation · Comédie"},
  {t:"Only Murders in the Building", plat:"disney", type:"serie", rating:8.1, year:2021, genre:"Comédie · Policier"},
  {t:"Family Guy (Les Griffin)", plat:"disney", type:"serie", rating:8.1, year:1999, genre:"Animation · Comédie"},
  {t:"Reservation Dogs", plat:"disney", type:"serie", rating:8.1, year:2021, genre:"Comédie · Drame"},
  {t:"American Horror Story", plat:"disney", type:"serie", rating:8.0, year:2011, genre:"Horreur · Drame"},
  {t:"Jessica Jones", plat:"disney", type:"serie", rating:7.9, year:2015, genre:"Super-héros · Crime"},
  {t:"WandaVision", plat:"disney", type:"serie", rating:7.9, year:2021, genre:"Super-héros · Mystère"},
  {t:"Grey's Anatomy", plat:"disney", type:"serie", rating:7.6, year:2005, genre:"Drame"},
  {t:"Hawkeye", plat:"disney", type:"serie", rating:7.5, year:2021, genre:"Super-héros · Action"},
  {t:"Ahsoka", plat:"disney", type:"serie", rating:7.5, year:2023, genre:"SF · Aventure"},
  {t:"Desperate Housewives", plat:"disney", type:"serie", rating:7.5, year:2004, genre:"Comédie · Drame"},
  {t:"The Old Man", plat:"disney", type:"serie", rating:7.4, year:2022, genre:"Drame · Thriller"},
  {t:"What If...?", plat:"disney", type:"serie", rating:7.3, year:2021, genre:"Animation · Super-héros"},
  {t:"Moon Knight", plat:"disney", type:"serie", rating:7.3, year:2022, genre:"Super-héros · Action"},
  {t:"Percy Jackson", plat:"disney", type:"serie", rating:7.0, year:2023, genre:"Aventure · Fantastique"},
  {t:"A Murder at the End of the World", plat:"disney", type:"serie", rating:7.0, year:2023, genre:"Mystère · Thriller"},
  {t:"L'Empire contre-attaque", plat:"disney", type:"film", rating:8.7, year:1980, genre:"SF · Aventure"},
  {t:"Un nouvel espoir", plat:"disney", type:"film", rating:8.6, year:1977, genre:"SF · Aventure"},
  {t:"Le Roi Lion", plat:"disney", type:"film", rating:8.5, year:1994, genre:"Animation · Famille"},
  {t:"Alien, le huitième passager", plat:"disney", type:"film", rating:8.5, year:1979, genre:"Horreur · SF"},
  {t:"Coco", plat:"disney", type:"film", rating:8.4, year:2017, genre:"Animation · Famille"},
  {t:"WALL-E", plat:"disney", type:"film", rating:8.4, year:2008, genre:"Animation · SF"},
  {t:"Avengers: Endgame", plat:"disney", type:"film", rating:8.4, year:2019, genre:"Super-héros · Action"},
  {t:"Avengers: Infinity War", plat:"disney", type:"film", rating:8.4, year:2018, genre:"Super-héros · Action"},
  {t:"Spider-Man: New Generation", plat:"disney", type:"film", rating:8.4, year:2018, genre:"Animation · Super-héros"},
  {t:"Aliens, le retour", plat:"disney", type:"film", rating:8.4, year:1986, genre:"Action · SF"},
  {t:"Indiana Jones et les Aventuriers de l'arche perdue", plat:"disney", type:"film", rating:8.4, year:1981, genre:"Aventure · Action"},
  {t:"Là-haut", plat:"disney", type:"film", rating:8.3, year:2009, genre:"Animation · Aventure"},
  {t:"Toy Story 3", plat:"disney", type:"film", rating:8.3, year:2010, genre:"Animation · Famille"},
  {t:"Toy Story", plat:"disney", type:"film", rating:8.3, year:1995, genre:"Animation · Famille"},
  {t:"Le Retour du Jedi", plat:"disney", type:"film", rating:8.3, year:1983, genre:"SF · Aventure"},
  {t:"Le Monde de Nemo", plat:"disney", type:"film", rating:8.2, year:2003, genre:"Animation · Famille"},
  {t:"Die Hard (Piège de cristal)", plat:"disney", type:"film", rating:8.2, year:1988, genre:"Action · Thriller"},
  {t:"Vice-versa", plat:"disney", type:"film", rating:8.1, year:2015, genre:"Animation · Famille"},
  {t:"Ratatouille", plat:"disney", type:"film", rating:8.1, year:2007, genre:"Animation · Comédie"},
  {t:"Monstres et Cie", plat:"disney", type:"film", rating:8.1, year:2001, genre:"Animation · Comédie"},
  {t:"Logan", plat:"disney", type:"film", rating:8.1, year:2017, genre:"Super-héros · Drame"},
  {t:"Pirates des Caraïbes : La Malédiction du Black Pearl", plat:"disney", type:"film", rating:8.1, year:2003, genre:"Aventure · Action"},
  {t:"Free Solo", plat:"disney", type:"film", rating:8.1, year:2018, genre:"Documentaire"},
  {t:"Les Indestructibles", plat:"disney", type:"film", rating:8.0, year:2004, genre:"Animation · Action"},
  {t:"Soul", plat:"disney", type:"film", rating:8.0, year:2020, genre:"Animation · Famille"},
  {t:"Zootopie", plat:"disney", type:"film", rating:8.0, year:2016, genre:"Animation · Comédie"},
  {t:"Aladdin", plat:"disney", type:"film", rating:8.0, year:1992, genre:"Animation · Famille"},
  {t:"La Belle et la Bête", plat:"disney", type:"film", rating:8.0, year:1991, genre:"Animation · Famille"},
  {t:"Les Gardiens de la Galaxie", plat:"disney", type:"film", rating:8.0, year:2014, genre:"Super-héros · Aventure"},
  {t:"Deadpool", plat:"disney", type:"film", rating:8.0, year:2016, genre:"Super-héros · Comédie"},
  {t:"Slumdog Millionaire", plat:"disney", type:"film", rating:8.0, year:2008, genre:"Drame"},
  {t:"Avengers", plat:"disney", type:"film", rating:8.0, year:2012, genre:"Super-héros · Action"},
  {t:"Iron Man", plat:"disney", type:"film", rating:7.9, year:2008, genre:"Super-héros · Action"},
  {t:"Avatar", plat:"disney", type:"film", rating:7.9, year:2009, genre:"SF · Aventure"},
  {t:"Titanic", plat:"disney", type:"film", rating:7.9, year:1997, genre:"Romance · Drame"},
  {t:"Thor: Ragnarok", plat:"disney", type:"film", rating:7.9, year:2017, genre:"Super-héros · Comédie"},
  {t:"Bohemian Rhapsody", plat:"disney", type:"film", rating:7.9, year:2018, genre:"Drame · Musique"},
  {t:"X-Men: Days of Future Past", plat:"disney", type:"film", rating:7.9, year:2014, genre:"Super-héros · Action"},
  {t:"Rogue One", plat:"disney", type:"film", rating:7.8, year:2016, genre:"SF · Aventure"},
  {t:"Captain America: Civil War", plat:"disney", type:"film", rating:7.8, year:2016, genre:"Super-héros · Action"},
  {t:"Predator", plat:"disney", type:"film", rating:7.8, year:1987, genre:"Action · SF"},
  {t:"Mary Poppins", plat:"disney", type:"film", rating:7.8, year:1964, genre:"Famille · Comédie musicale"},
  {t:"Les Nouveaux Héros", plat:"disney", type:"film", rating:7.8, year:2014, genre:"Animation · Action"},
  {t:"Raiponce", plat:"disney", type:"film", rating:7.7, year:2010, genre:"Animation · Famille"},
  {t:"Kingsman: Services secrets", plat:"disney", type:"film", rating:7.7, year:2014, genre:"Action · Comédie"},
  {t:"Vaiana", plat:"disney", type:"film", rating:7.6, year:2016, genre:"Animation · Famille"},
  {t:"Le Livre de la jungle", plat:"disney", type:"film", rating:7.6, year:1967, genre:"Animation · Famille"},
  {t:"Deadpool 2", plat:"disney", type:"film", rating:7.6, year:2018, genre:"Super-héros · Comédie"},
  {t:"Doctor Strange", plat:"disney", type:"film", rating:7.5, year:2016, genre:"Super-héros · Aventure"},
  {t:"The Greatest Showman", plat:"disney", type:"film", rating:7.5, year:2017, genre:"Comédie musicale · Drame"},
  {t:"Avatar: La Voie de l'eau", plat:"disney", type:"film", rating:7.5, year:2022, genre:"SF · Aventure"},
  {t:"La Reine des neiges", plat:"disney", type:"film", rating:7.4, year:2013, genre:"Animation · Famille"},
  {t:"Spider-Man: Homecoming", plat:"disney", type:"film", rating:7.4, year:2017, genre:"Super-héros · Action"},
  {t:"Black Panther", plat:"disney", type:"film", rating:7.3, year:2018, genre:"Super-héros · Action"},
  {t:"La Forme de l'eau", plat:"disney", type:"film", rating:7.3, year:2017, genre:"Drame · Fantastique"},
  {t:"Cars", plat:"disney", type:"film", rating:7.3, year:2006, genre:"Animation · Famille"},
  {t:"Encanto", plat:"disney", type:"film", rating:7.2, year:2021, genre:"Animation · Famille"},
  {t:"Rebelle", plat:"disney", type:"film", rating:7.1, year:2012, genre:"Animation · Aventure"},
  {t:"Le Diable s'habille en Prada", plat:"disney", type:"film", rating:7.0, year:2006, genre:"Comédie · Drame"},
  {t:"Élémentaire", plat:"disney", type:"film", rating:7.0, year:2023, genre:"Animation · Famille"}
];
